name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Install Noto Color Emoji Font
      #   run: |
          # sudo apt update
          # sudo apt install -y fonts-noto-color-emoji
          # fc-cache -fv
          # fc-list | grep -i "noto"

      - name: Install Source Han Sans SC
        run: |
          mkdir -p ~/.local/share/fonts
          # 1. 思源黑体（Sans）
          wget -q https://github.com/adobe-fonts/source-han-sans/releases/latest/download/09_SourceHanSansSC.zip
          unzip 09_SourceHanSansSC.zip -d sans
          mv sans ~/.local/share/fonts
          fc-cache -fv ~/.local/share/fonts/sans
          fc-list 

      - name: Install JetBrainsMono NerdFont
        run: |
          wget -q https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz
          mkdir mono
          tar -xf JetBrainsMono.tar.xz -C mono
          mv mono ~/.local/share/fonts
          fc-cache -fv ~/.local/share/fonts/mono
          fc-list 

      - name: Install FiraCode Nerd Font
        run: |
          wget -q https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
          unzip FiraCode.zip -d FiraCode
          mv FiraCode ~/.local/share/fonts
          fc-cache -fv ~/.local/share/fonts/FiraCode
          fc-list 

      - name: Install FiraMono Nerd Font
        run: |
          wget -q https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraMono.zip
          unzip FiraMono.zip -d FiraMono
          mv FiraMono ~/.local/share/fonts
          fc-cache -fv ~/.local/share/fonts/FiraMono
          fc-list 

      - name: Update fonts.config
        run: |
          mkdir -p ~/.config/fontconfig
          mv .github/fonts.conf ~/.config/fontconfig
          fc-cache -fv

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci

      - name: Prepare deploy folder
        run: rm -rf dist && mkdir dist

      - name: Install playwright for generating PDFs
        run: pnpm exec playwright install

      - name: Build all slides and preview app as index
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build

    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
